version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./docker/nginx/:/etc/nginx/conf.d
        - ./:/var/www
    networks:
      - app-network

  php-fpm:
    build: .
    volumes:
      - ./:/var/www
      - ~/.bashrc:/home/www/.bashrc
      - ~/.gitconfig:/home/www/.gitconfig
    networks:
      - app-network

  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      # PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/postgres/:/var/lib/postgresql/
    ports:
      - "5432:5432"
    networks:
        - app-network

networks:
  app-network:
    driver: bridge
