version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./docker/nginx/:/etc/nginx/conf.d
        - ./:/var/www
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build: .
    volumes:
      - ./:/var/www
      - ~/.bashrc:/home/www/.bashrc
      - ~/.gitconfig:/home/www/.gitconfig
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
#    ports:
#      - "9110:9110"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./docker/postgres/:/var/lib/postgresql/
    ports:
      - "5432:5432"
    networks:
        - app-network

networks:
  app-network:
    driver: bridge
